### ISSUE TITLE
[Improvement] Crosshatch pattern for pattern shape tool

### ISSUE THREAD

**Issue by Syrious** [neovatar/dungeondraft-dysonesque#4]
Hey there. I really love that pack. Would it be possible though to add the crosshatch to the pattern shape tool? Using the terrain brush it's hard to not overdraw a wall and paint the inside of a room. Especially for mega dungeons I assume using the pattern tool would be much easier and faster.

Thanks in advance!

**Comment by neovatar** [comment]
Thanks, added it in https://github.com/neovatar/dungeondraft-dysonesque/releases/tag/v2.5.0
